version: '3.8'
services:
  backend:
    build:
      context: ./proshop_django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./proshop_django:/app
      - ./proshop_django/static:/app/static # Dodany wolumin dla katalogu 'static'
      - ./proshop_django/staticfiles:/app/staticfiles # Dodany wolumin dla katalogu 'staticfiles'
      - ./proshop_django/media:/app/media # Dodany wolumin dla katalogu 'media'
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./proshop_django/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./proshop_django/frontend:/app
      - /app/node_modules

  # Jeśli chcesz użyć Nginx do serwowania plików statycznych, dodaj tutaj odpowiednią konfigurację
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./proshop_django/static:/usr/share/nginx/html/static
  #     - ./proshop_django/media:/usr/share/nginx/html/media
  #   # Dodaj tutaj odpowiedni plik konfiguracyjny Nginx

volumes:
  static_volume: # Definicja woluminu dla plików statycznych
  media_volume: # Definicja woluminu dla plików media
